name: matches
description: For LeadsDoIt.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  http: ^0.13.5
  webview_flutter: ^4.0.0
  webview_flutter_android: ^3.0.0
  webview_flutter_wkwebview: ^3.0.0
  flutter_bloc: ^8.1.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  intl: ^0.18.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/
    - assets/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
